apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: fmf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: fmf_server:1.0.0
        env:
          - name: PG_HOST
            value: "postgres"
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-password
                key: password
          - name: PG_USER
            value: "postgres"
          - name: PG_PORT
            value: "5432"
          - name: PG_DATABASE
            value: "crono_db"
        ports:
        - containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
   name: server
   namespace: fmf
   labels:
      app: server
   annotations: 
spec:
   selector:
     app: server
   ports:
   - port: 80
     targetPort: 5000
     protocol: TCP
