export const data = new webix.DataCollection({
  data: [{
      "Codice evento": 1,
      "Data inizio": "0000/00/00",
      "Data fine": "0000/00/00",
      "Luogo": "Lorem ipsum dolor sit amet",
      "Titolo": "consectetur",
      "Tipo evento": "eiusmod tempor incididunt",
      "Argomento": "elit",
      "Descrizione": " adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do",
      "Persone coinvolte": "dolore magna aliqua.",
      "MF": true,
      "Video": "laboris nisi ut aliquip ex ea commodo consequat.",
      "Multimedia": "exercitation ullamco ",
      "Audio": "lor in reprehenderit",
      "Foto": "Excepteur sint occaecat",
      "Stampa": "Ut enim ad minim veniam,",
      "Bibliografia": " quis nostrud",
      "Note": "Diploma di laurea?",
      "Link": "anim id"
    },
    {
      "Codice evento": 2,
      "Data inizio": "0000/00/00",
      "Data fine": "0000/00/00",
      "Luogo": "Lorem ipsum dolor sit amet",
      "Titolo": "consectetur",
      "Tipo evento": "eiusmod tempor incididunt",
      "Argomento": "elit",
      "Descrizione": " adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do",
      "Persone coinvolte": "dolore magna aliqua.",
      "MF": true,
      "Video": "laboris nisi ut aliquip ex ea commodo consequat.",
      "Multimedia": "exercitation ullamco ",
      "Audio": "lor in reprehenderit",
      "Foto": "Excepteur sint occaecat",
      "Stampa": "Ut enim ad minim veniam,",
      "Bibliografia": " quis nostrud",
      "Note": "Diploma di laurea?",
      "Link": "anim id"
    },
    {
      "Codice evento": 3,
      "Data inizio": "0000/00/00",
      "Data fine": "0000/00/00",
      "Luogo": "Lorem ipsum dolor sit amet",
      "Titolo": "consectetur",
      "Tipo evento": "eiusmod tempor incididunt",
      "Argomento": "elit",
      "Descrizione": " adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do",
      "Persone coinvolte": "dolore magna aliqua.",
      "MF": true,
      "Video": "laboris nisi ut aliquip ex ea commodo consequat.",
      "Multimedia": "exercitation ullamco ",
      "Audio": "lor in reprehenderit",
      "Foto": "Excepteur sint occaecat",
      "Stampa": "Ut enim ad minim veniam,",
      "Bibliografia": " quis nostrud",
      "Note": "Diploma di laurea?",
      "Link": "anim id"
    }, {
      "Codice evento": 1,
      "Data inizio": "0000/00/00",
      "Data fine": "0000/00/00",
      "Luogo": "Lorem ipsum dolor sit amet",
      "Titolo": "consectetur",
      "Tipo evento": "eiusmod tempor incididunt",
      "Argomento": "elit",
      "Descrizione": " adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do",
      "Persone coinvolte": "dolore magna aliqua.",
      "MF": true,
      "Video": "laboris nisi ut aliquip ex ea commodo consequat.",
      "Multimedia": "exercitation ullamco ",
      "Audio": "lor in reprehenderit",
      "Foto": "Excepteur sint occaecat",
      "Stampa": "Ut enim ad minim veniam,",
      "Bibliografia": " quis nostrud",
      "Note": "Diploma di laurea?",
      "Link": "anim id"
    },
    {
      "Codice evento": 4,
      "Data inizio": "0000/00/00",
      "Data fine": "0000/00/00",
      "Luogo": "Lorem ipsum dolor sit amet",
      "Titolo": "consectetur",
      "Tipo evento": "eiusmod tempor incididunt",
      "Argomento": "elit",
      "Descrizione": " adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do",
      "Persone coinvolte": "dolore magna aliqua.",
      "MF": true,
      "Video": "laboris nisi ut aliquip ex ea commodo consequat.",
      "Multimedia": "exercitation ullamco ",
      "Audio": "lor in reprehenderit",
      "Foto": "Excepteur sint occaecat",
      "Stampa": "Ut enim ad minim veniam,",
      "Bibliografia": " quis nostrud",
      "Note": "Diploma di laurea?",
      "Link": "anim id"
    },
    {
      "Codice evento": 5,
      "Data inizio": "0000/00/00",
      "Data fine": "0000/00/00",
      "Luogo": "Lorem ipsum dolor sit amet",
      "Titolo": "consectetur",
      "Tipo evento": "eiusmod tempor incididunt",
      "Argomento": "elit",
      "Descrizione": " adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do adipiscing elit, sed do",
      "Persone coinvolte": "dolore magna aliqua.",
      "MF": true,
      "Video": "laboris nisi ut aliquip ex ea commodo consequat.",
      "Multimedia": "exercitation ullamco ",
      "Audio": "lor in reprehenderit",
      "Foto": "Excepteur sint occaecat",
      "Stampa": "Ut enim ad minim veniam,",
      "Bibliografia": " quis nostrud",
      "Note": "Diploma di laurea?",
      "Link": "anim id"
    },
  ]
});
